# Generated by Django 5.1.6 on 2026-04-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0016_positionreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionposting',
            name='job_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
