# Generated by Codex on 2026-04-13

from django.db import migrations, models


def populate_performance_rating_applicability(apps, schema_editor):
    RecruitmentApplication = apps.get_model("recruitment", "RecruitmentApplication")
    EvidenceVaultItem = apps.get_model("recruitment", "EvidenceVaultItem")

    performance_rating_document_codes = set(
        EvidenceVaultItem.objects.filter(
            artifact_scope="application",
            artifact_type="applicant_document",
            stage="applicant_intake",
            is_current_version=True,
            is_archived=False,
            document_key="performance_rating",
        ).values_list("application_id", flat=True)
    )

    RecruitmentApplication.objects.exclude(
        id__in=performance_rating_document_codes
    ).update(performance_rating_applicability="not_applicable")


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0017_alter_positionposting_job_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentapplication",
            name="performance_rating_applicability",
            field=models.CharField(
                choices=[
                    ("applicable", "I have a performance rating for the last rating period"),
                    ("not_applicable", "I do not have an applicable performance rating"),
                ],
                default="applicable",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            populate_performance_rating_applicability,
            migrations.RunPython.noop,
        ),
    ]
