# Generated by Django 5.1.6 on 2026-04-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0018_recruitmentapplication_performance_rating_applicability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningrecord',
            name='completeness_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='screeningrecord',
            name='screening_notes',
            field=models.TextField(blank=True),
        ),
    ]
