# Generated by Django 5.1.6 on 2026-05-07 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0019_alter_screeningrecord_completeness_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrecord',
            name='administered_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='evidence_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_records', to='recruitment.evidencevaultitem'),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='practical_result',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='practical_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='technical_result',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='technical_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
