# Generated by Django 5.1.6 on 2026-05-07 03:01

from decimal import Decimal

from django.db import migrations, models


def normalize_exam_policy_values(apps, schema_editor):
    ExamRecord = apps.get_model("recruitment", "ExamRecord")
    for record in ExamRecord.objects.all():
        if record.branch == "cos":
            record.exam_type = "end_user_assessment"
        elif record.level == 2:
            record.exam_type = "technical_practical"
        else:
            record.exam_type = "general_practical"

        administered_by = (record.administered_by or "").lower()
        if "accredited" in administered_by or "academe" in administered_by or "up" == administered_by.strip():
            record.administered_by = "accredited_institution"
        elif "end-user" in administered_by or "end user" in administered_by:
            record.administered_by = "hrms_end_user" if "hrms" in administered_by else "end_user"
        elif record.administered_by:
            record.administered_by = "hrms"

        if record.exam_status == "completed":
            record.technical_result = "recorded" if record.technical_score is not None else "not_applicable"
            record.practical_result = "recorded" if record.practical_score is not None else "not_applicable"
            if record.exam_type in {"general_practical", "technical_practical"}:
                if record.technical_score is not None and record.practical_score is not None:
                    record.exam_score = (
                        (record.technical_score * Decimal("0.40"))
                        + (record.practical_score * Decimal("0.60"))
                    ).quantize(Decimal("0.01"))
            elif record.exam_type == "end_user_assessment" and record.practical_score is not None:
                record.exam_score = record.practical_score
            record.exam_result = "for_evaluation" if record.exam_score is not None else "incomplete"
        elif record.exam_status == "waived":
            record.exam_score = None
            record.technical_score = None
            record.practical_score = None
            record.technical_result = ""
            record.practical_result = ""
            record.exam_result = "waived"
        elif record.exam_status == "absent":
            record.exam_score = None
            record.technical_score = None
            record.practical_score = None
            record.technical_result = ""
            record.practical_result = ""
            record.exam_result = "absent"

        record.save(
            update_fields=[
                "exam_type",
                "administered_by",
                "exam_score",
                "exam_result",
                "technical_score",
                "technical_result",
                "practical_score",
                "practical_result",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0020_examrecord_administered_by_examrecord_evidence_item_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_exam_policy_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='examrecord',
            name='administered_by',
            field=models.CharField(blank=True, choices=[('hrms', 'Human Resource Management Section'), ('hrms_end_user', 'HRMS with End-user technical input'), ('end_user', 'End-user'), ('accredited_institution', 'UP or accredited institution/academe')], max_length=40),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='exam_result',
            field=models.CharField(blank=True, choices=[('for_evaluation', 'For HRMPSB evaluation'), ('incomplete', 'Incomplete'), ('waived', 'Waived'), ('absent', 'Absent')], max_length=40),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='exam_type',
            field=models.CharField(choices=[('general_practical', 'General and Practical Examination'), ('technical_practical', 'Technical and Practical / General Ability Test'), ('psychometric', 'Psychometric Examination'), ('end_user_assessment', 'End-user Examination')], max_length=40),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='practical_result',
            field=models.CharField(blank=True, choices=[('recorded', 'Recorded for evaluation'), ('not_applicable', 'Not applicable')], max_length=40),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='technical_result',
            field=models.CharField(blank=True, choices=[('recorded', 'Recorded for evaluation'), ('not_applicable', 'Not applicable')], max_length=40),
        ),
    ]
