# Generated by Django 5.1.6 on 2026-05-12 08:53

from django.db import migrations, models


def normalize_exam_type_to_hiring_process(apps, schema_editor):
    ExamRecord = apps.get_model("recruitment", "ExamRecord")
    ExamRecord.objects.filter(branch="plantilla").exclude(
        exam_type="technical_practical"
    ).update(exam_type="technical_practical")
    ExamRecord.objects.filter(branch="cos").exclude(
        exam_type="end_user_assessment"
    ).update(exam_type="end_user_assessment")


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0021_alter_examrecord_administered_by_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_exam_type_to_hiring_process, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='examrecord',
            name='exam_type',
            field=models.CharField(choices=[('technical_practical', 'Technical and Practical Examination'), ('end_user_assessment', 'End-user Examination')], max_length=40),
        ),
    ]
