# Generated by Django 5.1.6 on 2026-05-12 09:12

from django.db import migrations, models


def normalize_administered_by_to_hiring_process(apps, schema_editor):
    ExamRecord = apps.get_model("recruitment", "ExamRecord")
    ExamRecord.objects.filter(branch="cos").exclude(administered_by="").update(
        administered_by="end_user"
    )
    ExamRecord.objects.filter(branch="plantilla").exclude(administered_by="").update(
        administered_by="hrms"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0022_alter_examrecord_exam_type'),
    ]

    operations = [
        migrations.RunPython(
            normalize_administered_by_to_hiring_process,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='administered_by',
            field=models.CharField(blank=True, choices=[('hrms', 'Human Resource Management Section'), ('end_user', 'End-user')], max_length=40),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='exam_result',
            field=models.CharField(blank=True, choices=[('for_evaluation', 'For evaluation'), ('incomplete', 'Incomplete'), ('waived', 'Waived'), ('absent', 'Absent')], max_length=40),
        ),
    ]
