# Generated by Django 5.1.6 on 2026-05-17 17:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0024_alter_auditlog_action_internalmfachallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by_role', models.CharField(blank=True, max_length=40)),
                ('decision_notes', models.TextField()),
                ('car_snapshot', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-decided_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='comparativeassessmentreport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_finalized', True)), fields=('recruitment_entry', 'review_stage'), name='unique_finalized_car_per_entry_stage'),
        ),
        migrations.AddField(
            model_name='finalselection',
            name='comparative_assessment_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='final_selection', to='recruitment.comparativeassessmentreport'),
        ),
        migrations.AddField(
            model_name='finalselection',
            name='decided_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_final_selections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finalselection',
            name='recruitment_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_selections', to='recruitment.positionposting'),
        ),
        migrations.AddField(
            model_name='finalselection',
            name='selected_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_selections_as_selected', to='recruitment.recruitmentapplication'),
        ),
        migrations.AddField(
            model_name='finalselection',
            name='selected_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_selections_as_selected', to='recruitment.recruitmentcase'),
        ),
        migrations.AddField(
            model_name='finalselection',
            name='selected_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='final_selection', to='recruitment.comparativeassessmentreportitem'),
        ),
        migrations.AddConstraint(
            model_name='finalselection',
            constraint=models.UniqueConstraint(fields=('recruitment_entry',), name='unique_final_selection_per_entry'),
        ),
    ]
