# Generated by Django 5.1.6 on 2026-05-20 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_rating_encoder(apps, schema_editor):
    InterviewRating = apps.get_model("recruitment", "InterviewRating")
    for rating in InterviewRating.objects.filter(encoded_by__isnull=True).iterator():
        rating.encoded_by_id = rating.rated_by_id
        rating.encoded_by_role = rating.rated_by_role
        rating.save(update_fields=["encoded_by", "encoded_by_role"])


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0025_final_selection_car_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewrating',
            name='encoded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encoded_interview_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewrating',
            name='encoded_by_role',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.RunPython(backfill_rating_encoder, migrations.RunPython.noop),
    ]
