# Generated by Django 5.1.6 on 2026-05-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0026_interview_rating_encoder'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativeassessmentreportitem',
            name='assessment_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='comparativeassessmentreportitem',
            name='document_review_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='comparativeassessmentreportitem',
            name='preliminary_rank_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparativeassessmentreportitem',
            name='ranking_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='screeningrecord',
            name='document_review_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='screeningrecord',
            name='education_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='screeningrecord',
            name='experience_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='screeningrecord',
            name='training_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
