# Generated by Django 5.1.6 on 2026-05-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0027_comparativeassessmentreportitem_assessment_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliberationrecord",
            name="comparative_assessment_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deliberation_records",
                to="recruitment.comparativeassessmentreport",
            ),
        ),
        migrations.AddField(
            model_name="deliberationrecord",
            name="recommendation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="deliberationrecord",
            name="quorum_status",
            field=models.CharField(
                choices=[
                    ("not_recorded", "Not Recorded"),
                    ("met", "Met"),
                    ("not_met", "Not Met"),
                ],
                default="not_recorded",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="deliberationrecord",
            name="attendance_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="comparativeassessmentreportitem",
            name="deliberation_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comparative_assessment_report_items",
                to="recruitment.deliberationrecord",
            ),
        ),
        migrations.AddField(
            model_name="comparativeassessmentreportitem",
            name="recommendation",
            field=models.TextField(blank=True),
        ),
    ]
