# Generated by Django 5.1.6 on 2026-05-20 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0028_hrmpsb_car_draft_deliberation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comparativeassessmentreport',
            name='unique_finalized_car_per_entry_stage',
        ),
        migrations.AddField(
            model_name='comparativeassessmentreport',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comparativeassessmentreport',
            name='return_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comparativeassessmentreport',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparativeassessmentreport',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_comparative_assessment_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comparativeassessmentreport',
            name='returned_by_role',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='finalselection',
            name='deep_selection_justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalselection',
            name='is_deep_selection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('internal_login', 'Internal Login'), ('internal_logout', 'Internal Logout'), ('internal_mfa_sent', 'Internal MFA Sent'), ('internal_mfa_resent', 'Internal MFA Resent'), ('internal_mfa_verified', 'Internal MFA Verified'), ('internal_mfa_failed', 'Internal MFA Failed'), ('internal_mfa_expired', 'Internal MFA Expired'), ('internal_mfa_locked', 'Internal MFA Locked'), ('password_changed', 'Password Changed'), ('internal_account_created', 'Internal Account Created'), ('internal_account_updated', 'Internal Account Updated'), ('internal_account_activated', 'Internal Account Activated'), ('internal_account_deactivated', 'Internal Account Deactivated'), ('internal_role_changed', 'Internal Role Changed'), ('position_created', 'Position Created'), ('position_updated', 'Position Updated'), ('recruitment_entry_created', 'Recruitment Entry Created'), ('recruitment_entry_updated', 'Recruitment Entry Updated'), ('recruitment_entry_status_changed', 'Recruitment Entry Status Changed'), ('application_created', 'Application Created'), ('application_updated', 'Application Updated'), ('application_otp_sent', 'Application OTP Sent'), ('application_otp_verified', 'Application OTP Verified'), ('application_submitted', 'Application Submitted'), ('case_created', 'Case Created'), ('case_reopened', 'Case Reopened'), ('routed', 'Application Routed'), ('screening_recorded', 'Screening Recorded'), ('screening_finalized', 'Screening Finalized'), ('exam_recorded', 'Exam Recorded'), ('exam_finalized', 'Exam Finalized'), ('interview_scheduled', 'Interview Scheduled'), ('interview_finalized', 'Interview Finalized'), ('interview_rating_recorded', 'Interview Rating Recorded'), ('interview_fallback_uploaded', 'Interview Fallback Uploaded'), ('deliberation_recorded', 'Deliberation Recorded'), ('deliberation_finalized', 'Deliberation Finalized'), ('car_generated', 'Comparative Assessment Report Generated'), ('car_finalized', 'Comparative Assessment Report Finalized'), ('car_returned', 'Comparative Assessment Report Returned'), ('decision_recorded', 'Decision Recorded'), ('completion_recorded', 'Completion Recorded'), ('case_closed', 'Case Closed'), ('notification_sent', 'Notification Sent'), ('notification_failed', 'Notification Failed'), ('override_granted', 'Override Granted'), ('override_used', 'Override Used'), ('evidence_uploaded', 'Evidence Uploaded'), ('evidence_downloaded', 'Evidence Downloaded'), ('evidence_archived', 'Evidence Archived'), ('evidence_restored', 'Evidence Restored'), ('protected_record_viewed', 'Protected Record Viewed'), ('evidence_vault_viewed', 'Evidence Vault Viewed'), ('audit_log_viewed', 'Audit Log Viewed'), ('export_generated', 'Export Generated')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='comparativeassessmentreport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_finalized', True), ('is_returned', False)), fields=('recruitment_entry', 'review_stage'), name='unique_active_finalized_car_per_entry_stage'),
        ),
    ]
