# Generated by Django 5.1.6 on 2026-05-20 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0029_remove_comparativeassessmentreport_unique_finalized_car_per_entry_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningDocumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_key', models.CharField(max_length=150)),
                ('requirement_title', models.CharField(max_length=255)),
                ('requirement_label', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('meets', 'Meets'), ('needs_review', 'Needs Review'), ('absent', 'Absent'), ('not_applicable', 'Not Applicable')], default='not_reviewed', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('is_not_applicable', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('evidence_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_document_reviews', to='recruitment.evidencevaultitem')),
                ('screening_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_reviews', to='recruitment.screeningrecord')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['document_key', 'status'], name='recruitment_documen_e6ba1b_idx'), models.Index(fields=['status', 'is_required'], name='recruitment_status_5a2c10_idx')],
                'constraints': [models.UniqueConstraint(fields=('screening_record', 'document_key'), name='unique_screening_document_review_per_record')],
            },
        ),
    ]
