# Generated by Django 5.1.6 on 2026-05-21 01:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0030_screeningdocumentreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('internal_login', 'Internal Login'), ('internal_login_failed', 'Internal Login Failed'), ('internal_login_locked', 'Internal Login Locked'), ('internal_logout', 'Internal Logout'), ('internal_mfa_sent', 'Internal MFA Sent'), ('internal_mfa_resent', 'Internal MFA Resent'), ('internal_mfa_verified', 'Internal MFA Verified'), ('internal_mfa_failed', 'Internal MFA Failed'), ('internal_mfa_expired', 'Internal MFA Expired'), ('internal_mfa_locked', 'Internal MFA Locked'), ('password_changed', 'Password Changed'), ('internal_account_created', 'Internal Account Created'), ('internal_account_updated', 'Internal Account Updated'), ('internal_account_activated', 'Internal Account Activated'), ('internal_account_deactivated', 'Internal Account Deactivated'), ('internal_role_changed', 'Internal Role Changed'), ('position_created', 'Position Created'), ('position_updated', 'Position Updated'), ('recruitment_entry_created', 'Recruitment Entry Created'), ('recruitment_entry_updated', 'Recruitment Entry Updated'), ('recruitment_entry_status_changed', 'Recruitment Entry Status Changed'), ('application_created', 'Application Created'), ('application_updated', 'Application Updated'), ('application_otp_sent', 'Application OTP Sent'), ('application_otp_verified', 'Application OTP Verified'), ('application_submitted', 'Application Submitted'), ('case_created', 'Case Created'), ('case_reopened', 'Case Reopened'), ('routed', 'Application Routed'), ('screening_recorded', 'Screening Recorded'), ('screening_finalized', 'Screening Finalized'), ('exam_recorded', 'Exam Recorded'), ('exam_finalized', 'Exam Finalized'), ('interview_scheduled', 'Interview Scheduled'), ('interview_finalized', 'Interview Finalized'), ('interview_rating_recorded', 'Interview Rating Recorded'), ('interview_fallback_uploaded', 'Interview Fallback Uploaded'), ('deliberation_recorded', 'Deliberation Recorded'), ('deliberation_finalized', 'Deliberation Finalized'), ('car_generated', 'Comparative Assessment Report Generated'), ('car_finalized', 'Comparative Assessment Report Finalized'), ('car_returned', 'Comparative Assessment Report Returned'), ('decision_recorded', 'Decision Recorded'), ('completion_recorded', 'Completion Recorded'), ('case_closed', 'Case Closed'), ('notification_sent', 'Notification Sent'), ('notification_failed', 'Notification Failed'), ('override_granted', 'Override Granted'), ('override_used', 'Override Used'), ('evidence_uploaded', 'Evidence Uploaded'), ('evidence_downloaded', 'Evidence Downloaded'), ('evidence_archived', 'Evidence Archived'), ('evidence_restored', 'Evidence Restored'), ('protected_record_viewed', 'Protected Record Viewed'), ('evidence_vault_viewed', 'Evidence Vault Viewed'), ('audit_log_viewed', 'Audit Log Viewed'), ('export_generated', 'Export Generated')], max_length=50),
        ),
        migrations.CreateModel(
            name='InternalLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=150)),
                ('username_normalized', models.CharField(max_length=150)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.TextField(blank=True)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
                ('first_failed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_failed_at', '-updated_at'],
                'indexes': [models.Index(fields=['username_normalized', 'ip_address'], name='recruitment_usernam_00697f_idx'), models.Index(fields=['locked_until'], name='recruitment_locked__0f9144_idx')],
                'constraints': [models.UniqueConstraint(fields=('username_normalized', 'ip_address'), name='unique_internal_login_attempt_key')],
            },
        ),
    ]
