# Generated by Django 5.2.14 on 2026-05-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0032_alter_auditlog_action_internalemailchangerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningdocumentreview',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('submission_acknowledgment', 'Submission Acknowledgment'), ('selected_applicant', 'Selected Applicant Notification'), ('non_selected_applicant', 'Non-selected Applicant Notification'), ('document_resubmission_request', 'Document Resubmission Request'), ('requirement_checklist', 'Requirement Checklist Notification'), ('reminder', 'Reminder Notification')], max_length=40),
        ),
        migrations.AlterField(
            model_name='screeningdocumentreview',
            name='status',
            field=models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('meets', 'Meets'), ('needs_review', 'Needs Review'), ('request_resubmission', 'Request Resubmission'), ('absent', 'Absent'), ('not_applicable', 'Not Applicable')], default='not_reviewed', max_length=20),
        ),
    ]
