# Generated by Django 5.2.14 on 2026-05-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0034_application_returned_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('submission_acknowledgment', 'Submission Acknowledgment'), ('selected_applicant', 'Selected Applicant Notification'), ('non_selected_applicant', 'Non-selected Applicant Notification'), ('document_resubmission_request', 'Document Resubmission Request'), ('application_returned_to_applicant', 'Application Returned to Applicant Notification'), ('interview_session_scheduled', 'Interview Session Scheduled Notification'), ('requirement_checklist', 'Requirement Checklist Notification'), ('reminder', 'Reminder Notification')], max_length=40),
        ),
    ]
