# Generated by Django 5.2.14 on 2026-05-23 16:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_stage_entered_at(apps, schema_editor):
    recruitment_case = apps.get_model('recruitment', 'RecruitmentCase')
    recruitment_case.objects.update(stage_entered_at=models.F('updated_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0035_interview_schedule_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentcase',
            name='stage_entered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(backfill_stage_entered_at, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('case_assigned', 'Case assigned to you'), ('case_returned', 'Case returned to you'), ('screening_finalized', 'Screening finalized'), ('resubmission_received', 'Resubmission received'), ('interview_scheduled', 'Interview session scheduled'), ('interview_finalized', 'Interview session finalized'), ('deadline_approaching', 'Deadline approaching')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=400)),
                ('related_url', models.CharField(blank=True, max_length=400)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to='recruitment.recruitmentapplication')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', 'created_at'], name='notif_rec_read_created_idx')],
            },
        ),
    ]
