# Generated by Django 5.2.15 on 2026-06-25 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0037_recruitmentapplication_otp_attempt_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('internal_login', 'Internal Login'), ('internal_login_failed', 'Internal Login Failed'), ('internal_login_locked', 'Internal Login Locked'), ('internal_login_alert_sent', 'Internal Login Alert Sent'), ('internal_login_alert_failed', 'Internal Login Alert Failed'), ('internal_logout', 'Internal Logout'), ('internal_mfa_sent', 'Internal MFA Sent'), ('internal_mfa_resent', 'Internal MFA Resent'), ('internal_mfa_verified', 'Internal MFA Verified'), ('internal_mfa_failed', 'Internal MFA Failed'), ('internal_mfa_expired', 'Internal MFA Expired'), ('internal_mfa_locked', 'Internal MFA Locked'), ('password_changed', 'Password Changed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_completed', 'Password Reset Completed'), ('internal_account_created', 'Internal Account Created'), ('internal_account_updated', 'Internal Account Updated'), ('internal_email_change_requested', 'Internal Email Change Requested'), ('internal_email_change_verified', 'Internal Email Change Verified'), ('internal_email_change_failed', 'Internal Email Change Failed'), ('internal_account_activated', 'Internal Account Activated'), ('internal_account_deactivated', 'Internal Account Deactivated'), ('internal_role_changed', 'Internal Role Changed'), ('position_created', 'Position Created'), ('position_updated', 'Position Updated'), ('recruitment_entry_created', 'Recruitment Entry Created'), ('recruitment_entry_updated', 'Recruitment Entry Updated'), ('recruitment_entry_status_changed', 'Recruitment Entry Status Changed'), ('application_created', 'Application Created'), ('application_updated', 'Application Updated'), ('application_otp_sent', 'Application OTP Sent'), ('application_otp_failed', 'Application OTP Failed'), ('application_otp_locked', 'Application OTP Locked'), ('application_otp_verified', 'Application OTP Verified'), ('application_submitted', 'Application Submitted'), ('case_created', 'Case Created'), ('case_reopened', 'Case Reopened'), ('routed', 'Application Routed'), ('screening_recorded', 'Screening Recorded'), ('screening_finalized', 'Screening Finalized'), ('exam_scheduled', 'Exam Scheduled'), ('exam_recorded', 'Exam Recorded'), ('exam_finalized', 'Exam Finalized'), ('interview_scheduled', 'Interview Scheduled'), ('interview_finalized', 'Interview Finalized'), ('interview_rating_recorded', 'Interview Rating Recorded'), ('interview_fallback_uploaded', 'Interview Fallback Uploaded'), ('deliberation_recorded', 'Deliberation Recorded'), ('deliberation_finalized', 'Deliberation Finalized'), ('car_generated', 'Comparative Assessment Report Generated'), ('car_finalized', 'Comparative Assessment Report Finalized'), ('car_returned', 'Comparative Assessment Report Returned'), ('decision_recorded', 'Decision Recorded'), ('completion_recorded', 'Completion Recorded'), ('case_closed', 'Case Closed'), ('notification_sent', 'Notification Sent'), ('notification_failed', 'Notification Failed'), ('override_granted', 'Override Granted'), ('override_used', 'Override Used'), ('evidence_uploaded', 'Evidence Uploaded'), ('evidence_downloaded', 'Evidence Downloaded'), ('evidence_archived', 'Evidence Archived'), ('evidence_restored', 'Evidence Restored'), ('evidence_access_denied', 'Evidence Access Denied'), ('protected_record_viewed', 'Protected Record Viewed'), ('evidence_vault_viewed', 'Evidence Vault Viewed'), ('audit_log_viewed', 'Audit Log Viewed'), ('export_generated', 'Export Generated'), ('export_denied', 'Export Denied')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('submission_acknowledgment', 'Submission Acknowledgment'), ('selected_applicant', 'Selected Applicant Notification'), ('non_selected_applicant', 'Non-selected Applicant Notification'), ('document_resubmission_request', 'Document Resubmission Request'), ('application_returned_to_applicant', 'Application Returned to Applicant Notification'), ('interview_session_scheduled', 'Interview Session Scheduled Notification'), ('exam_invitation', 'Exam Invitation Notification'), ('applicant_interview_notice', 'Applicant Interview Notice Notification'), ('requirement_checklist', 'Requirement Checklist Notification'), ('reminder', 'Reminder Notification')], max_length=40),
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_stage', models.CharField(choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('completion', 'Completion Tracking'), ('closed', 'Closed')], max_length=40)),
                ('scheduled_by_role', models.CharField(blank=True, max_length=40)),
                ('branch', models.CharField(choices=[('plantilla', 'Plantilla'), ('cos', 'COS')], max_length=20)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')])),
                ('scheduled_for', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('notice_delivery', models.CharField(choices=[('system_email', 'Emailed to applicant'), ('printed_notice', 'Hand-delivered printed notice')], default='system_email', max_length=20)),
                ('applicant_notified_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='recruitment.recruitmentapplication')),
                ('recruitment_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='recruitment.recruitmentcase')),
                ('recruitment_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_schedules', to='recruitment.positionposting')),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_exam_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['review_stage', 'scheduled_for', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('application', 'review_stage'), name='unique_exam_schedule_per_application_stage')],
            },
        ),
    ]
