# Generated by Django 5.2.15 on 2026-06-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0039_rename_exam_general_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examrecord',
            name='exam_type',
            field=models.CharField(choices=[('technical_practical', 'Examination (General and Technical)'), ('end_user_assessment', 'End-user Examination')], max_length=40),
        ),
    ]
