# Generated by Django 5.2.15 on 2026-06-28 22:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0041_positionposting_item_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyRatingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_role', models.CharField(blank=True, max_length=40)),
                ('scale_min', models.PositiveSmallIntegerField(default=1)),
                ('scale_max', models.PositiveSmallIntegerField(default=4)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_competency_rating_templates', to=settings.AUTH_USER_MODEL)),
                ('recruitment_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='competency_rating_template', to='recruitment.positionposting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(choices=[('core', 'Core'), ('organizational', 'Organizational'), ('technical', 'Technical')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='recruitment.competencyratingtemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
