# Generated by Django 5.2.15 on 2026-06-29 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0043_alter_auditlog_action_assessmentweightconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField()),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='recruitment.competencydefinition')),
                ('interview_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_scores', to='recruitment.interviewrating')),
            ],
            options={
                'ordering': ['competency__order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('interview_rating', 'competency'), name='unique_competency_score_per_rating')],
            },
        ),
    ]
