# Generated by Django 5.2.15 on 2026-06-29 18:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0044_competencyscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentweightconfig',
            name='ete_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='assessmentweightconfig',
            name='exam_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='assessmentweightconfig',
            name='interview_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5),
        ),
    ]
