# Generated by Django 5.2.15 on 2026-06-29 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0045_assessmentweightconfig_ete_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativeassessmentreportitem',
            name='ete_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='ApplicationETERating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recorded_by_role', models.CharField(blank=True, max_length=40)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ete_rating', to='recruitment.recruitmentapplication')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_ete_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
