# Generated by Django 5.2.15 on 2026-06-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0046_comparativeassessmentreportitem_ete_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativeassessmentreport',
            name='members_present',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparativeassessmentreport',
            name='quorum_met',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
