# Generated by Django 5.2.15 on 2026-06-30 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0047_comparativeassessmentreport_members_present_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_code', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='recruitment.positionposting')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('posting', 'document_code'), name='unique_document_requirement_per_posting')],
            },
        ),
    ]
