# Generated by Django 5.2.15 on 2026-06-30 10:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0048_positiondocumentrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyAssessmentWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_general_weight', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5)),
                ('exam_technical_weight', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5)),
                ('ete_weight', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5)),
                ('exam_weight', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('interview_weight', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('recruitment_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_weights', to='recruitment.positionposting')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacancy assessment weights',
                'verbose_name_plural': 'Vacancy assessment weights',
            },
        ),
    ]
