# Generated by Django 5.2.15 on 2026-06-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0049_vacancyassessmentweights'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssessmentWeightConfig',
        ),
    ]
