# Generated by Django 5.2.15 on 2026-06-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0050_delete_assessmentweightconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningrecord',
            name='resubmission_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screeningrecord',
            name='resubmission_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentcase',
            name='case_status',
            field=models.CharField(choices=[('active', 'Active'), ('returned_to_applicant', 'Returned to Applicant'), ('awaiting_resubmission', 'Awaiting Resubmission'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='active', max_length=40),
        ),
    ]
