# Generated by Django 5.2.15 on 2026-06-30 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0052_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativeassessmentreport',
            name='recommendation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comparativeassessmentreport',
            name='recommended_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recommended_in_comparative_assessment_reports', to='recruitment.recruitmentcase'),
        ),
    ]
