# Generated by Django 5.2.15 on 2026-06-30 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0053_comparativeassessmentreport_recommendation_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosVacancyDeliberation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by_role', models.CharField(blank=True, max_length=40)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_by_role', models.CharField(blank=True, max_length=40)),
                ('chosen_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chosen_in_cos_vacancy_deliberations', to='recruitment.recruitmentcase')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_cos_vacancy_deliberations', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_cos_vacancy_deliberations', to=settings.AUTH_USER_MODEL)),
                ('recruitment_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cos_vacancy_deliberation', to='recruitment.positionposting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
