# Generated by Django 5.2.15 on 2026-06-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0054_cosvacancydeliberation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningdocumentreview',
            name='status',
            field=models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('meets', 'Meets'), ('request_resubmission', 'Request Resubmission'), ('absent', 'Absent'), ('not_applicable', 'Not Applicable')], default='not_reviewed', max_length=20),
        ),
    ]
